const UserActions = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  LOGOUT: 'LOGOUT',

  FETCH_POST: 'FETCH_POSTS',
  FET_POST_DETAIL: 'FETCH_POST_DETAIL',

  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  EDIT_POST: 'EDIT_POST',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
};

export default UserActions;
